networks:
  ingress:
    name: ingress
    external: true
volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
services:
  nextcloud-aio-mastercontainer:
    image: nextcloud/all-in-one:latest
    restart: unless-stopped
    init: true
    container_name: nextcloud-aio-mastercontainer # This line is not allowed to be changed as otherwise AIO will not work correctly
    volumes:
      - nextcloud_aio_mastercontainer:/mnt/docker-aio-config # This line is not allowed to be changed as otherwise the built-in backup solution will not work
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      ingress:
        aliases:
          - nextcloud-aio-mastercontainer
          - aio
    environment:
      - APACHE_IP_BINDING=0.0.0.0
      - APACHE_PORT=11000
      - SKIP_DOMAIN_VALIDATION=true
