networks:
  internal:
  ingress:
    name: 'ingress'
    external: true
volumes:
  db:
  wordpress:

services:
  terminal_space:
    image: ghcr.io/intentionally-left-nil/wordpress-nginx:main
    restart: unless-stopped
    init: true
    volumes:
      - wordpress:/var/www/html:ro
    networks:
      - internal
      - ingress
  php:
    image: ghcr.io/intentionally-left-nil/wordpress-php:main
    restart: unless-stopped
    init: true
    env_file:
      - ./secrets/.env
    volumes:
      - wordpress:/var/www/html
    networks:
      - internal

  wp-cron:
    build:
      context: './cron'
    restart: unless-stopped
    init: true
    env_file:
      - ./secrets/.env
    volumes:
      - wordpress:/var/www/html

    networks:
      - internal

  db:
    image: mariadb:11-jammy
    restart: unless-stopped
    init: true
    env_file:
      - ./secrets/.env
    volumes:
      - db:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test:
        [
          'CMD',
          '/usr/local/bin/healthcheck.sh',
          '--connect',
          '--innodb_initialized',
        ]
      interval: 5s
      timeout: 5s
      retries: 10
