volumes:
  data:
    name: reverse-proxy-data
networks:
  ingress:
    name: 'ingress'
services:
  proxy:
    image: ghcr.io/intentionally-left-nil/reverse-proxy:main
    restart: unless-stopped
    init: true
    volumes:
      - ./secrets/config.json:/etc/reverse_proxy/config.json
      - data:/etc/reverse_proxy/data
    networks:
      - ingress
    ports:
      - '80:80'
      - '443:443'
